version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    volumes:
      - ./front/dist:/root/front/dist

  redis:
    image: redis:7-alpine
    container_name: redis-stockflow
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:

